{% set name = "fast-cdr" %}
{% set version = "1.0.19" %}
{% set major_minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eProsima/Fast-CDR/archive/v{{ version }}.tar.gz
    sha256: ba6635676a86db319a1cfb265336cd1cfe126ccb89f362054b400364addbe356

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\fastcdr-{{ major_minor_version }}.dll exit 1  # [win]
    - test -f $PREFIX/lib/libfastcdr${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libfastcdr${SHLIB_EXT}.{{ version }}  # [linux]
    - test -f $PREFIX/include/fastcdr/Cdr.h  # [unix]

about:
  home: https://github.com/eProsima/Fast-CDR
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    eProsima FastCDR
  description: |
    eProsima FastCDR library provides two serialization mechanisms. One is the
    standard CDR serialization mechanism, while the other is a faster
    implementation of it.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - MiguelCompany
    - EduPonz
