{% set name = "fast-cdr" %}
{% set version = "1.0.14" %}
{% set major_minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eProsima/Fast-CDR/archive/v{{ version }}.tar.gz
    sha256: 43af2b6f335a561f60564d4fbf47bbb67cbdf898a692413cf7c17a226143b93f

build:
  number: 0
  skip: true  # [win and vc<14 or unix]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\fastcdr-{{ major_minor_version }}.dll exit 1  # [win]

about:
  home: https://github.com/eProsima/Fast-CDR
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    eProsima FastCDR

extra:
  recipe-maintainers:
    - seanyen
